### ISSUE TITLE
UNINITIALIZED - HANDLER_INITIALIZING_ERROR rocks.xmpp.core.session.Module: Provider rocks.xmpp.core.session.context.CoreContext not a subtype

### ISSUE THREAD

**Issue by Salve87** [ruebox/openhab2-addons#16]
Hello, 
I tried installing the binding hundreds of times. newest version 
I  always get this message when connecting the Bridge:
UNINITIALIZED - HANDLER_INITIALIZING_ERROR rocks.xmpp.core.session.Module: Provider rocks.xmpp.core.session.context.CoreContext not a subtype

I tried the "Installer" account.  I tried the "jid":  account. used older versions. 

Can you please help me. I can't find the mistake.

Btw: I have the B+J Weather station. Can I support with the integration into this Binding?

**Comment by Salve87** [comment]
I also tried installing "XMPP Action" but it didn't help with the problem

**Comment by ruebox** [comment]
Hi.
In general the binding is self contained. You do not have to install additional stuff. Just copy the jar to the addon folder.
I sometimes have this problem, but only if I have several sessions running in parallel. 

Do you have the correct port 5280?
Does the problem persist after restarting openhab?
Which firmware version are you using?

Best

**Comment by lassem** [comment]
I see this from time to time myself; restarting the service usually helps.

**Comment by Salve87** [comment]
Hey guys,
thanks for the replies. I restarted openHAB and free@home. No success
I copied the Jar to the add-on folder. Startet the binding in Inbox manually.
I'm using openHAB 2.3.0 Build #1231 and free@home version 2.1.6 revision 5966.

**Comment by ruebox** [comment]
@Salve87 Did you have success? At least with the correct parameters and after restart of openhab the connection should be established.

**Comment by Salve87** [comment]
Hey Guys,
I gave up on the issue. 
@ruebox: your comment made me work on the problem again.
I updated the Free@home Firmware to 2.1.7
I removed a folder Openhab/xmpp.rocks

NOW IT WORKS :-) great. Thanks guys!!!!

Btw: I have the B+J Weather station. Can I support with the integration into this Binding?

**Comment by butterfly1640** [comment]
Hi,
I have a similar problem. The FreeAtHome Bridge won't connect. Status: UNINITIALIZED - HANDLER_INITIALIZING_ERROR Session is not connected to server.

I copied the jar to the folder add-on
Added the binding in the inbox manually
I started OpenHab several times - but nothing happened

Has anyone a solution? Thanks

-----
Free@home Firmware to 2.1.7
openHAB 2.2.0
the port is 5280

my OpenHab.log

2018-06-05 13:18:43.642 [INFO ] [er.internal.HomeBuilderDashboardTile] - Started Home Builder at /homebuilder
2018-06-05 13:18:44.095 [WARN ] [g.eclipse.smarthome.core.net.NetUtil] - Found multiple local interfaces - ignoring 192.168.11.1
2018-06-05 13:18:44.095 [WARN ] [g.eclipse.smarthome.core.net.NetUtil] - Found multiple local interfaces - ignoring 192.168.1.12
2018-06-05 13:18:44.142 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.182.1:8080
2018-06-05 13:18:44.142 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.182.1:8443
2018-06-05 13:18:47.486 [INFO ] [thome.model.lsp.internal.ModelServer] - Started Language Server Protocol (LSP) service on port 5007
2018-06-05 13:18:48.345 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2018-06-05 13:18:48.361 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2018-06-05 13:18:48.392 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2018-06-05 13:18:48.907 [ERROR] [home.handler.FreeAtHomeBridgeHandler] - Login on SysAP with login name: installer (Login name could not be resolved)
2018-06-05 13:18:48.907 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.freeathome.handler.FreeAtHomeBridgeHandler@7072f3db': Session is not connected to server
java.lang.IllegalStateException: Session is not connected to server
	at rocks.xmpp.core.session.XmppSession.send(XmppSession.java:653) [195:org.openhab.binding.freeathome:1.0.0.201806011929]
	at rocks.xmpp.core.session.XmppClient.send(XmppClient.java:467) [195:org.openhab.binding.freeathome:1.0.0.201806011929]
	at org.openhab.binding.freeathome.handler.FreeAtHomeBridgeHandler.connectGateway(FreeAtHomeBridgeHandler.java:413) [195:org.openhab.binding.freeathome:1.0.0.201806011929]
	at org.openhab.binding.freeathome.handler.FreeAtHomeBridgeHandler.initialize(FreeAtHomeBridgeHandler.java:133) [195:org.openhab.binding.freeathome:1.0.0.201806011929]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2018-06-05 13:18:48.907 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while initializing handler of thing 'freeathome:bridge:88d99679': Session is not connected to server
java.lang.IllegalStateException: Session is not connected to server
	at rocks.xmpp.core.session.XmppSession.send(XmppSession.java:653) [195:org.openhab.binding.freeathome:1.0.0.201806011929]
	at rocks.xmpp.core.session.XmppClient.send(XmppClient.java:467) [195:org.openhab.binding.freeathome:1.0.0.201806011929]
	at org.openhab.binding.freeathome.handler.FreeAtHomeBridgeHandler.connectGateway(FreeAtHomeBridgeHandler.java:413) [195:org.openhab.binding.freeathome:1.0.0.201806011929]
	at org.openhab.binding.freeathome.handler.FreeAtHomeBridgeHandler.initialize(FreeAtHomeBridgeHandler.java:133) [195:org.openhab.binding.freeathome:1.0.0.201806011929]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2018-06-05 15:45:19.977 [ERROR] [home.handler.FreeAtHomeBridgeHandler] - Can not connect to IP gateway
2018-06-05 15:45:19.977 [ERROR] [home.handler.FreeAtHomeBridgeHandler] - javax.xml.bind.JAXBException: Weder class rocks.xmpp.extensions.httpbind.model.Body noch eine der zugehörigen Superklassen ist diesem Kontext bekannt.
2018-06-05 15:45:20.008 [WARN ] [home.handler.FreeAtHomeBridgeHandler] - Could not successfully get the getAll.xml from sysAP. Can happen if connecting to server takes too long.

**Comment by Salve87** [comment]
Hello,
When i have that problem, i restart my Raspberry Pi via ssh.

**Comment by ruebox** [comment]
Hi

I think the root cause is the login:
Login on SysAP with login name: installer (Login name could not be resolved)

The login is case sensitive. Could you please check : Installer

With capital I.

Please remove the bridge thing and add a new instance.

Best

**Comment by Salve87** [comment]
I have that Problem with all usernames including Installer (Json)

**Comment by butterfly1640** [comment]
Thanks for your help. But the problem still exists.

I checked the word installer => they are both the same
I changed installer to Installer
I removed the bridge thing and added a new instance

I have to mention, I use a win10 installation - Could that be the problem?

**Comment by ruebox** [comment]
Could you please send me a log. 

What you can also try out with Installer login.
Login to official webui.
In different tab login to openhab. 

Thx

**Comment by ruebox** [comment]
Win 10 is not tested till now. I was only working on Linux.

**Comment by butterfly1640** [comment]
Hey guys,

now it is working. The FreeATHome Bridge is online. I don't know why. The only thing I did, I turned on my computer this morning.

Thanks for your help.
