### ISSUE TITLE
Cant find any devices

### ISSUE THREAD

**Issue by Raatiw** [ruebox/openhab2-addons#51]
The bridge is online, but somehow the devices are never discovered or in the inbox.
I've tried updating the SysAP to v2.2.6 (was 2.2.4) but als no luck. Is there something I'm missing in my configuration? The user has installation rights. I've tried different settings. Enabled the free@home API. But no luck. Also no dummy devices sho up. The devices are all wireless 1 or 2 actuator sensor switches and lights. 
I've tried adding a dummy switch with a know ID. But also that doesn't work.

```

2019-07-11 15:11:15.396 [hingStatusInfoChangedEvent] - 'freeathome:bridge:83386ffa' changed from INITIALIZING to ONLINE.

==> /var/log/openhab2/openhab.log <==

2019-07-11 15:11:21.387 [ERROR] [home.handler.FreeAtHomeBridgeHandler] - XMPP Exception: Timeout reached, while waiting on a response for request: IQ-set (445b505e-47d2-4f4d-b88d-a37969938b12) to 'mrha@busch-jaeger.de/rpc

Extension(s):

RemoteInterface.getAll(de, 4, 0, 0)

2019-07-11 15:11:21.095 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot trigger scan for thing types '[freeathome:dimmer, freeathome:raffstore, freeathome:bridge, freeathome:thermostat, freeathome:dummy, freeathome:switch, freeathome:weather, freeathome:scene, freeathome:scenario_selector]' on 'FreeAtHomeBindingDiscoveryService'!

java.lang.IllegalStateException: Cannot send stanzas before resource binding has completed.

	at rocks.xmpp.core.session.XmppSession.sendInternal(XmppSession.java:887) ~[?:?]

	at rocks.xmpp.core.session.XmppSession.trackAndSend(XmppSession.java:1002) ~[?:?]

	at rocks.xmpp.core.session.XmppSession.sendIQ(XmppSession.java:975) ~[?:?]

	at rocks.xmpp.core.session.XmppSession.sendAndAwait(XmppSession.java:824) ~[?:?]

	at rocks.xmpp.core.session.XmppSession.query(XmppSession.java:750) ~[?:?]

	at rocks.xmpp.core.session.XmppSession.query(XmppSession.java:735) ~[?:?]

	at rocks.xmpp.extensions.rpc.RpcManager.call(RpcManager.java:113) ~[?:?]

	at org.openhab.binding.freeathome.handler.FreeAtHomeBridgeHandler.getAll(FreeAtHomeBridgeHandler.java:197) ~[?:?]

	at org.openhab.binding.freeathome.discovery.FreeAtHomeBindingDiscoveryService.startScan(FreeAtHomeBindingDiscoveryService.java:57) ~[?:?]

	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:211) ~[98:org.eclipse.smarthome.config.discovery:0.10.0.oh240]

	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:381) [98:org.eclipse.smarthome.config.discovery:0.10.0.oh240]

	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:366) [98:org.eclipse.smarthome.config.discovery:0.10.0.oh240]

	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:215) [98:org.eclipse.smarthome.config.discovery:0.10.0.oh240]

	at org.eclipse.smarthome.io.rest.core.internal.discovery.DiscoveryResource.scan(DiscoveryResource.java:97) [120:org.eclipse.smarthome.io.rest.core:0.10.0.oh240]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [171:org.glassfish.jersey.core.jersey-common:2.22.2]

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [171:org.glassfish.jersey.core.jersey-common:2.22.2]

	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [171:org.glassfish.jersey.core.jersey-common:2.22.2]

	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [171:org.glassfish.jersey.core.jersey-common:2.22.2]

	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [171:org.glassfish.jersey.core.jersey-common:2.22.2]

	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [171:org.glassfish.jersey.core.jersey-common:2.22.2]

	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [172:org.glassfish.jersey.core.jersey-server:2.22.2]

	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) [169:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]

	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) [169:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) [169:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) [169:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) [169:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]

	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76) [20:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) [85:org.eclipse.jetty.servlet:9.4.11.v20180605]

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) [85:org.eclipse.jetty.servlet:9.4.11.v20180605]

	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [186:org.ops4j.pax.web.pax-web-jetty:7.2.3]

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [82:org.eclipse.jetty.security:9.4.11.v20180605]

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:293) [186:org.ops4j.pax.web.pax-web-jetty:7.2.3]

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [85:org.eclipse.jetty.servlet:9.4.11.v20180605]

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [186:org.ops4j.pax.web.pax-web-jetty:7.2.3]

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.Server.handle(Server.java:531) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [84:org.eclipse.jetty.server:9.4.11.v20180605]

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [75:org.eclipse.jetty.io:9.4.11.v20180605]

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [75:org.eclipse.jetty.io:9.4.11.v20180605]

	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [75:org.eclipse.jetty.io:9.4.11.v20180605]

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [87:org.eclipse.jetty.util:9.4.11.v20180605]

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [87:org.eclipse.jetty.util:9.4.11.v20180605]

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [87:org.eclipse.jetty.util:9.4.11.v20180605]

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [87:org.eclipse.jetty.util:9.4.11.v20180605]

	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [87:org.eclipse.jetty.util:9.4.11.v20180605]

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) [87:org.eclipse.jetty.util:9.4.11.v20180605]

	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) [87:org.eclipse.jetty.util:9.4.11.v20180605]

	at java.lang.Thread.run(Thread.java:748) 
```

2019-07-11 15:11:22.834 [WARN ] [home.handler.FreeAtHomeBridgeHandler] - Could not successfully get the getAll.xml from sysAP. Can happen if connecting to server takes too long.

**Comment by Raatiw** [comment]
It turns out that the devices I've got in my home are all wireless. They are identified with deviceId 2039. Both dimmer and switches. These are not yet supported here. I've tried to get the developer environment with this branch working, but I've got a lot of errors for this branch. (Somehow the Addon development is out of sync here with the latest OpenHab setup, but maybe someone can help me out there)

The switches are controllable trough ch0006 and the dimmer trough ch0008. See below for the json dump i've made with the https://github.com/sstadlberger/home nodejs API implementation. I've adde the devices there to the dimmer settings and i can controll them trough that. It actually works the same as the normal dimmer and normal switch. The only strange thing is that both type of devices are identified with deviceId 2039. 

{
  "ABB700CB193D": {
        "serialNumber": "ABB700CB193B",
        "deviceId": "2039",
        "typeName": "Sensor/Dimmaktor 1/1-fach",
        "channels": {
            "ch0008": {
                "datapoints": {
                    "idp0000": "0",
                    "idp0001": "0",
                    "idp0005": "0",
                    "idp0006": "0",
                    "odp0000": "0",
                    "odp0001": "0",
                    "odp0002": "0",
                    "odp0003": "0",
                    "pm0000": "3",
                    "pm0001": "1",
                    "pm0002": "100",
                    "pm0003": "100",
                    "pm0004": "360",
                    "pm0005": "1"
                }
            },
            "ch000D": {
                "datapoints": {
                    "idp0000": "300",
                    "odp0000": "34",
                    "odp0001": "39390",
                    "odp0002": "300"
                }
            }
        }
    },
    "ABB700CB1918": {
        "serialNumber": "ABB700CB1917",
        "deviceId": "2039",
        "typeName": "Sensor/ Schaltaktor 1/1-fach",
        "channels": {
            "ch0006": {
                "datapoints": {
                    "idp0000": "0",
                    "idp0003": "0",
                    "odp0000": "0",
                    "odp0001": "0",
                    "pm0000": "360",
                    "pm0001": "1"
                }
            },
            "ch000D": {
                "datapoints": {
                    "idp0000": "300",
                    "odp0000": "34",
                    "odp0001": "24051",
                    "odp0002": "300"
                }
            }
        }
    }
}
[infodump.zip](https://github.com/ruebox/openhab2-addons/files/3472057/infodump.zip)
