### ISSUE TITLE
Bug With Unit of "Wetterstation" "Wind Speed"

### ISSUE THREAD

**Issue by LuiSauberhorn** [ruebox/openhab2-addons#55]
Hi ruebox,

first of all, very good job! I used your binding to create some sophisticated rules for our free@home system. Works really good so far.

However, I found an interesting bug. Checking the openhab.log, I get the following warning from time to time:

`2020-03-29 19:15:48.554 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener 'org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl@3a26c8' about state update of item SmartHome_WetterstationWindSpeed: Can not compare incompatible units.
java.lang.IllegalArgumentException: Can not compare incompatible units.
	at org.eclipse.smarthome.core.library.types.QuantityType.compareTo(QuantityType.java:174) ~[bundleFile:?]
	at org.eclipse.smarthome.core.library.types.QuantityType.equals(QuantityType.java:156) ~[bundleFile:?]
	at org.eclipse.smarthome.core.items.GenericItem$1.run(GenericItem.java:260) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]`

Checking the events.log, I see the following events that correlate:

`2020-03-29 19:14:41.163 [vent.ItemStateChangedEvent] - SmartHome_WetterstationWindSpeed changed from 1.22 m/s to 1.64 m/s
2020-03-29 19:14:55.134 [vent.ItemStateChangedEvent] - SmartHome_WetterstationWindSpeed changed from 1.64 m/s to 1.55 m/s
2020-03-29 19:14:58.339 [vent.ItemStateChangedEvent] - SmartHome_WetterstationWindSpeed changed from 1.55 m/s to 1.68 m/s
2020-03-29 19:14:59.287 [vent.ItemStateChangedEvent] - SmartHome_WetterstationWindSpeed changed from 1.68 m/s to 3.48 m/s
2020-03-29 19:15:01.468 [vent.ItemStateChangedEvent] - SmartHome_WetterstationWindSpeed changed from 3.48 m/s to 3.26 m/s
2020-03-29 19:15:42.418 [vent.ItemStateChangedEvent] - SmartHome_WetterstationWindSpeed changed from 3.26 m/s to 1.59 m/s
2020-03-29 19:15:54.840 [vent.ItemStateChangedEvent] - SmartHome_WetterstationWindSpeed changed from 1.65 m² to 1.54 m/s
2020-03-29 19:15:55.859 [vent.ItemStateChangedEvent] - SmartHome_WetterstationWindSpeed changed from 1.54 m/s to 1.65 m/s
2020-03-29 19:16:09.845 [vent.ItemStateChangedEvent] - SmartHome_WetterstationWindSpeed changed from 1.65 m/s to 1.58 m/s`

You can see that there is at least one event missing for a timestamp around 2020-03-29 19:15:48:

- Last before is 2020-03-29 19:15:42.418: The value changes from 3.26 m/s to 1.59 m/s
- Next event after that is 2020-03-29 19:15:54.840, the "from value" is not 1.59 m/s 

However, the problem becomes obvious here: In the first event after 2020-03-29 19:15:48.554, you can see that the "from" value has the unit m² instead of m/s. That does not make sense for wind speed. Any clue where this is coming from? For me, that looks like a bug.

Let me know if I can help somehow...

Best, Lui

**Comment by LuiSauberhorn** [comment]
Update title

**Comment by LuiSauberhorn** [comment]
Hi ruebox,

are you still actively developing this binding?

If so, I would like to contribute. I manually integrated thinks like "wind alarm notification" or "window sensors" and we could try to bring that as default features back into your code. Happy to work on the code...

Thanks Lui

**Comment by Cuver77** [comment]
@LuiSauberhorn 

Hi Lui, please have a look at the following link: https://community.openhab.org/t/busch-jaeger-free-home/31043/234

The binding is currently being maintained and developed by a some other people based on the code of ruebox. Window sensors are already integrated. The wind alarm notification feature sounds very interesting.
